# Understanding the `numpy.ndarray` internals

In [1]:
import numpy as np

In [2]:
x = np.array([[0, 1, 2, 3],[4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]], dtype=np.int8)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]], dtype=int8)

In [3]:
x.strides

(4, 1)

***
### 1. Understanding strides
<mark>Question</mark>: Determine the strides for the following arrays. Check your answer with `x.strides`.

In [5]:
# 1.1
y = x.reshape((2, 8))
y

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]], dtype=int8)

In [6]:
y.strides

(8, 1)

In [7]:
# 1.2
z = x.reshape((1, 16))
z

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]],
      dtype=int8)

In [8]:
z.strides

(16, 1)

In [12]:
# 1.3
a = np.array([[0, 1, 2, 3],[4, 5, 6, 7],[8, 9, 10, 11], [12, 13, 14, 15]], dtype=np.int16)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]], dtype=int16)

In [13]:
a.strides

(8, 2)

In [20]:
b = np.array([[0,1,2]], dtype=np.float64)
print(b)
b.strides

[[0. 1. 2.]]


(24, 8)

***
### 2. Metadata modification vs copying the data buffer

<mark>Question</mark>: How do you explain the next result? Is the result the same when using `x.flatten()` instead of `x.ravel()`?

> Note: Both `flatten()` and `ravel()` return a flattend version of an array.

In [22]:
x = np.arange(5)
print('x =', x)

y = x.ravel()  #  assign to y a flattened version the array x
y[0] = 5       #  change the first element of the array y

print('\nx =', x)

x = [0 1 2 3 4]

x = [5 1 2 3 4]


In [24]:
a = np.arange(5)
print('a =', a)

b = a.flatten()  #  assign to y a flattened version the array x
b[0] = 5       #  change the first element of the array y
print('\nb =', b)
print('\na =', a)

a = [0 1 2 3 4]

b = [5 1 2 3 4]

a = [0 1 2 3 4]


<mark>Question</mark>: The next three cells do the same two operations: transposing a matrix and flattening it. How do you explain the difference in execution time?

In [25]:
x = np.random.rand(5000, 5000)

In [26]:
%%timeit
# 2.1
x.T
x.ravel()

389 ns ± 1.24 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [27]:
%%timeit
# 2.2
x.T
x.flatten()

94.8 ms ± 223 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [28]:
%%timeit
# 2.3
x.T.ravel()

396 ms ± 281 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
